/**
 * The shipped **spawn-brother** skill (ADR-0013): the SKILL.md that teaches an
 * agent inside a run to request sibling runs through its runtime-broker, plus
 * the script that does the HTTP call (the bundled, type-checked `./cli.ts`,
 * run with the harness image's own `node`). Selecting this skill for a run is
 * what plans the broker sidecar.
 */

import { SPAWN_BROTHER_CLI_BUNDLE } from './bundle.generated.js';
import {
  RUN_REPORTS_DIR,
  RUN_REPORT_FILE,
  SPAWN_BROTHER_SCRIPT,
  SPAWN_BROTHER_SKILL,
} from './constants.js';
import type { SkillFiles } from '../skill/index.js';

const SKILL_MD =
  [
    '---',
    `name: ${SPAWN_BROTHER_SKILL}`,
    'description: Request a sibling run (a "brother" agent) from inside an e run through the runtime-broker; check, wait for, or cancel it. Use when a task splits into independent parts another agent should take on in parallel.',
    '---',
    '',
    '# Spawn a brother (sibling run)',
    '',
    'You are inside an e run. The host set `$E_ROLE` (`parent` | `child`) and',
    '`$E_BROKER_URL` (the runtime-broker endpoint) in your environment. Roles are',
    'env, never files: do not create or look for parent/child marker files.',
    '',
    `This skill directory holds \`${SPAWN_BROTHER_SCRIPT}\`; run it with \`node\` (every`,
    'harness image has one). It lives where your harness loads skills from, e.g.',
    `\`~/.agents/skills/${SPAWN_BROTHER_SKILL}/${SPAWN_BROTHER_SCRIPT}\` (pi, codex, opencode) or`,
    `\`~/.claude/skills/${SPAWN_BROTHER_SKILL}/${SPAWN_BROTHER_SCRIPT}\` (Claude Code).`,
    '',
    '## Request a sibling',
    '',
    '```bash',
    `node <skill dir>/${SPAWN_BROTHER_SCRIPT} <agent> "<the whole task: goal, scope, acceptance criteria, files, constraints>"`,
    '```',
    '',
    'Prints the accepted request as JSON: `{"id":"sib-001","status":"requested","statusPath":"/status/sib-001"}`.',
    'A refusal prints the JSON error and exits 1: `429` means the fan-out cap is',
    'full - retry after one of your siblings finishes; `403` means this run may',
    'not spawn (it is a sibling itself).',
    'The call is non-blocking: it queues the request for the host, which starts the',
    'sibling in the background while you keep working. Several siblings may run at',
    'once (the host caps them, default 3).',
    'Depth is two: you may request siblings; a sibling may request siblings; nobody',
    'gets grandchildren.',
    '',
    '## Check on siblings',
    '',
    '```bash',
    `node <skill dir>/${SPAWN_BROTHER_SCRIPT} --status            # every sibling of this run`,
    `node <skill dir>/${SPAWN_BROTHER_SCRIPT} --status sib-001    # one`,
    '```',
    '',
    'States: `requested` (spooled for the host) -> `starting` -> `running` -> `done`',
    "(carries the sibling's branch and exit code), `failed` (carries the error),",
    '`canceled` (you canceled it, or your run ended first) or `rejected` (the host',
    'refused it). Every record also carries `taskState`, the same lifecycle in the',
    'Agent2Agent (A2A) vocabulary: `submitted`, `working`, `input-required` (its',
    'merge-back waits for you: `conflict` or `held`), `completed`, `failed`,',
    '`canceled`, `rejected`. `taskState` is the one field to branch on.',
    'A request that stays `requested` is not being picked up: use the fallback below.',
    '',
    '## Wait for a sibling instead of polling',
    '',
    '```bash',
    `node <skill dir>/${SPAWN_BROTHER_SCRIPT} --watch            # until any sibling needs you`,
    `node <skill dir>/${SPAWN_BROTHER_SCRIPT} --watch sib-001    # until this one does`,
    '```',
    '',
    "Blocks on the broker's event stream (`GET /status/events`) and prints, as a",
    'JSON array, the siblings whose `taskState` is `input-required`, `completed`,',
    '`failed`, `canceled` or `rejected` - at once if one already is, otherwise as',
    'soon as one gets there. Exit 4 after 30 minutes without news: check `--status`.',
    'Keep working on your own part between spawning and watching; watch when you',
    'have nothing left to do without the sibling.',
    '',
    '## Cancel a sibling',
    '',
    '```bash',
    `node <skill dir>/${SPAWN_BROTHER_SCRIPT} --cancel sib-001`,
    '```',
    '',
    'Asks the host to stop the sibling (or never start it). Its status becomes',
    '`canceled`; nothing of it is merged (`merge.status: skipped`). `409` means it',
    'is already done, failed, canceled or rejected.',
    '',
    '## When a sibling finishes: the merge-back',
    '',
    'Once a sibling is `done`, the host merges its branch into your worktree - you',
    'never run git. Its status then carries `merge` and `report`:',
    '',
    `- \`report\`: \`${RUN_REPORTS_DIR}/<id>/${RUN_REPORT_FILE}\` in your worktree (\`/workspace\`) - read it; it`,
    '  says what happened and what, if anything, you must do.',
    "- `merge.status: merged`: the sibling's files are in your worktree now, as a",
    '  merge commit. Re-read any of them you had open. Your own uncommitted work was',
    '  checkpointed first; nothing of yours is lost.',
    "- `merge.status: up-to-date`: the sibling's branch added nothing to merge.",
    '- `merge.status: conflict`: the merge is in progress with conflict markers in',
    '  `merge.files`. Resolve each file by editing it (keep what is right, remove the',
    '  `<<<<<<<` / `=======` / `>>>>>>>` markers), then signal:',
    '',
    '```bash',
    `node <skill dir>/${SPAWN_BROTHER_SCRIPT} --merge <id>    # "resolved / cleared, retry the merge"`,
    '```',
    '',
    '  The host concludes the merge as a commit that also carries your current work.',
    '  Until you do, no other sibling can be merged, and the host never resolves a',
    '  conflict for you. If your run ends first, the host commits what it finds.',
    '- `merge.status: held`: your edits to `merge.files` were in flight when the host',
    '  tried. Finish and save them, then run `--merge <id>` as above; the host',
    '  checkpoints your work and retries. It also retries when your run ends with',
    '  exit code 0.',
    '- `merge.status: skipped` or `merge.status: failed`: not merged; `merge.reason` says why (the',
    '  sibling failed, exited non-zero, was canceled or rejected, was a remote A2A',
    "  agent without a branch, or git refused). The sibling's branch, when it had",
    '  one, is still named in its status.',
    '',
    '## Remote agents',
    '',
    'A Store agent may be a remote Agent2Agent (A2A) agent (`"transport": "a2a"`',
    'in its `agent.json`). Request it like any other: the host sends it your prompt',
    'over A2A and waits. It has no worktree and no branch: its answer is the',
    '`answer` field of its status and the body of its report; `merge.status` is',
    '`skipped`. Use it for questions and research, not for edits to this tree.',
    '',
    '## Without the script',
    '',
    '```bash',
    'curl -sS -X POST "$E_BROKER_URL/spawn" -H "content-type: application/json" -d \'{"agent":"<agent>","prompt":"<task>"}\'',
    'curl -sS "$E_BROKER_URL/status"',
    'curl -sN "$E_BROKER_URL/status/events"        # server-sent events, one `status` per change',
    'curl -sS -X POST "$E_BROKER_URL/merge/<id>"',
    'curl -sS -X POST "$E_BROKER_URL/cancel/<id>"',
    '```',
    '',
    '## If the broker does not answer',
    '',
    'The script exits 3 (connection refused / no `$E_BROKER_URL`): sibling spawning',
    'is unavailable in this run. Record the task and its acceptance criteria as a',
    'file in `/workspace`, exit 0, and let the parent (or the host) spawn the',
    'follow-up run.',
    '',
    '## Rules',
    '',
    '- Put everything the brother needs into the prompt; it has no access to your',
    '  conversation, only to a checkpoint of your worktree.',
    '- Never run git yourself; the host owns git for you and your siblings.',
    '- The role is `$E_ROLE`; never a marker file in the worktree.',
  ].join('\n') + '\n';

/** The files of the shipped `spawn-brother` skill. */
export function renderSpawnBrotherSkill(): SkillFiles {
  return {
    'SKILL.md': SKILL_MD,
    [SPAWN_BROTHER_SCRIPT]: SPAWN_BROTHER_CLI_BUNDLE,
  };
}
