// Bundles the runtime-broker server (src/sidecars/broker/server/server.ts) and the
// spawn-brother skill script (src/sidecars/broker/server/cli.ts) into two dependency-free ESM
// scripts and writes them as string constants to src/sidecars/broker/bundle.generated.ts,
// so `e init` / `e spawn` can seed them into the Store without reading any file
// at run time (which keeps the pkg binary self-contained). Runs before tsc in
// `build:ts`; tsc still type-checks the sources afterwards. Same approach as
// scripts/build-egress-api.mjs: container-shipped code is real, type-checked
// TS, never a string template.

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { bundleNodeOnly } from './bundle-node-script.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const target = path.join(
  root,
  'src',
  'sidecars',
  'broker',
  'bundle.generated.ts'
);

const server = await bundleNodeOnly(
  path.join(root, 'src', 'sidecars', 'broker', 'server', 'server.ts'),
  'runtime-broker server'
);
const cli = await bundleNodeOnly(
  path.join(root, 'src', 'sidecars', 'broker', 'server', 'cli.ts'),
  'spawn-brother script'
);

const generated = `// GENERATED by scripts/build-broker.mjs from src/sidecars/broker/server/server.ts and src/sidecars/broker/server/cli.ts.
// Do not edit; rebuild with \`npm run build:broker\`.
/* eslint-disable */
/** The self-contained runtime-broker server seeded into the broker build context. */
export const BROKER_SERVER_BUNDLE: string = ${JSON.stringify(server)};
/** The self-contained spawn-brother script seeded into the Store skill. */
export const SPAWN_BROTHER_CLI_BUNDLE: string = ${JSON.stringify(cli)};
`;
await fs.writeFile(target, generated);
console.log(`broker bundles written to ${path.relative(root, target)}`);
